### ISSUE TITLE
scss引入报错

### ISSUE THREAD

**Issue by waitkafuka** [jdf2e/nutui#50]
需要定制样式，按完整组件方式引入，根据官方文档在引入了`import '@nutui/nutui/nutui.scss';`之后，报错找不到文件。看了下`node_modules`文件夹下，并没有这个文件，dist下面倒是有。
将路径改为`import '@nutui/nutui/dist/nutui.scss';`之后，进而又报图片未找到的错误，信息如下：
```
* ../../assets/img/img-error.png in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-1-3!./node_modules/@nutui/nutui/dist/nutui.scss                                   friendly-errors 15:40:04
* ../../assets/img/img-loading.png in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-1-3!./node_modules/@nutui/nutui/dist/nutui.scss 
```
请问是哪里出了问题？

**Comment by Franslee** [comment]
已定到问题，下一个版本解决。你可以试试按需加载方式，只引入使用到的组件，而不是引入整个组件库。

**Comment by waitkafuka** [comment]
> 已定到问题，下一个版本解决。你可以试试按需加载方式，只引入使用到的组件，而不是引入整个组件库。

 好的，谢啦。然而你忘了我是用后端渲染没法用按需引入 #48 。。然而回复速度还是令人欣慰的，给了我使用下去的信心。加油，相信会越来越多的人使用。

**Comment by Franslee** [comment]
新版本已发布，此问题已修复，感谢反馈

**Comment by renleiabc** [comment]
我现在用的就是最新版本，但是问题依然存在

**Comment by renleiabc** [comment]
需要定制样式，按完整组件方式引入，根据官方文档在引入了import '@nutui/nutui/nutui.scss';之后，报错找不到文件。看了下node_modules文件夹下，并没有这个文件，dist下面倒是有。
将路径改为import '@nutui/nutui/dist/nutui.scss';之后，进而又报图片未找到的错误，信息如下：

* ../../assets/img/img-error.png in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/postcss-loader/src??ref--6-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-1-3!./node_modules/@nutui/nutui/dist/nutui.scss                                   friendly-errors 15:40:04
* ../../assets/img/img-loading.png in ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/po
我现在用的就是最新版本，但是问题依然存在

**Comment by richard1015** [comment]
@renleiabc   请参考demo   https://github.com/richard1015/nutui-demo

**Comment by renleiabc** [comment]
我这个是在nuxt当中使用的，不是在vue-cli3上使用的，请问有什么解决的办法吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "richard1015"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 中午11:21
收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 
抄送: "海阔天空"<421796896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jdf2e/nutui] scss引入报错 (#50)





 
@renleiabc   请参考demo   https://github.com/richard1015/nutui-demo

**Comment by renleiabc** [comment]
我这个是在nuxt当中使用的，不是在vue-cli3上使用的，请问有什么解决的办法吗？

**Comment by richard1015** [comment]
> 我这个是在nuxt当中使用的，不是在vue-cli3上使用的，请问有什么解决的办法吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "richard1015"<notifications@github.com&gt;; 发送时间: 2020年4月9日(星期四) 中午11:21 收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 抄送: "海阔天空"<421796896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [jdf2e/nutui] scss引入报错 (#50) @renleiabc 请参考demo https://github.com/richard1015/nutui-demo — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，我这边尽快跟进一下

**Comment by renleiabc** [comment]
谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "richard1015"<notifications@github.com&gt;; 
发送时间: 2020年4月9日(星期四) 中午11:26
收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 
抄送: "海阔天空"<421796896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [jdf2e/nutui] scss引入报错 (#50)





  
我这个是在nuxt当中使用的，不是在vue-cli3上使用的，请问有什么解决的办法吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "richard1015"<notifications@github.com&gt;; 发送时间: 2020年4月9日(星期四) 中午11:21 收件人: "jdf2e/nutui"<nutui@noreply.github.com&gt;; 抄送: "海阔天空"<421796896@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 主题: Re: [jdf2e/nutui] scss引入报错 (#50) @renleiabc 请参考demo https://github.com/richard1015/nutui-demo — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
好的，我这边尽快跟进一下
