### ISSUE TITLE
ShortPassword 短密码相关

### ISSUE THREAD

**Issue by lv7202215** [jdf2e/nutui#91]

**Comment by lv7202215** [comment]
第一个问题是：希望把忘记密码设置成可选择，有点项目用不到这个
第二个问题是：短密码第一次打开能获得焦点，但是关闭后再次打开,无法获得焦点，需要手动点一下密码框

**Comment by Franslee** [comment]
第一个问题，不错的建议，我们后续改进。作为临时方案，可以先通过自定义样式屏蔽。
第二个问题，我们排查一下。

**Comment by myzf** [comment]
想问下，用其他组件，点击后怎么才能弹出短密码，我把值设置成显示true，短密码死活出不来

**Comment by wangnan41** [comment]
你看一下例子代码，watch 改变才能显示吧发自我的iPhone------------------ 原始邮件 ------------------发件人: 曾金珍  <notifications@github.com>发送时间: 2019年7月27日 10:42收件人: jdf2e/nutui <nutui@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[jdf2e/nutui] ShortPassword 短密码相关 (#91)想问下，用其他组件，点击后怎么才能弹出短密码，我把值设置成显示true，短密码死活出不来

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jdf2e/nutui/issues/91?email_source=notifications\u0026email_token=ACG7SZARGAKZZYMBSATABOTQBOYXRA5CNFSM4HLE7J6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26CAHA#issuecomment-515645468",
"url": "https://github.com/jdf2e/nutui/issues/91?email_source=notifications\u0026email_token=ACG7SZARGAKZZYMBSATABOTQBOYXRA5CNFSM4HLE7J6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26CAHA#issuecomment-515645468",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
